// <auto-generated />
using System;
using Library.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.API.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20230804124541_Initial3")]
    partial class Initial3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.20");

            modelBuilder.Entity("Library.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fbd518e2-a6d1-4ea9-8cda-fceaf2703bcd"),
                            Author = "Harper Lee",
                            PublishDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A powerful novel set in the American South during the struggle for civil rights and social justice.",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("d6d555f0-c8a8-43ce-b4ad-ec51357efd21"),
                            Author = "George Orwell",
                            PublishDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A dystopian and political science fiction novel that depicts a society controlled by a totalitarian government.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("eafa5565-89ca-4101-aec0-3b791c05e4d4"),
                            Author = "F. Scott Fitzgerald",
                            PublishDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A distinctive novel that portrays the social elite in the 1920s.",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("f832ea23-d85a-4f1c-ba61-67bd6637a8d6"),
                            Author = "J.R.R. Tolkien",
                            PublishDate = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "An epic fantasy trilogy that follows the journey of Frodo Baggins and his friends to destroy the One Ring.",
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("8a6093bb-45e1-4f16-9d6f-c278dd0ea5b7"),
                            Author = "J.D. Salinger",
                            PublishDate = new DateTime(1951, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A famous novel that depicts teenage angst and social alienation.",
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = new Guid("47c5d7b1-2323-4a65-a654-3338cb6f3128"),
                            Author = "Aldous Huxley",
                            PublishDate = new DateTime(1932, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A science fiction novel that describes an advanced future society and how technology and institutions affect humans.",
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = new Guid("992d461e-4317-4859-baa2-194138253e09"),
                            Author = "Jane Austen",
                            PublishDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A classic romance novel that portrays British society in the 19th century.",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("9faea490-c621-429d-9964-b5ecc835f1f8"),
                            Author = "C.S. Lewis",
                            PublishDate = new DateTime(1950, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A series of seven fantasy novels that follow the adventures of children in the magical land of Narnia.",
                            Title = "The Chronicles of Narnia"
                        },
                        new
                        {
                            Id = new Guid("62064eb1-5a93-4772-8b82-c74fcf5294d5"),
                            Author = "Herman Melville",
                            PublishDate = new DateTime(1851, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "An epic novel that describes the journey of sailors aboard the ship 'Pequod' to hunt a giant whale named Moby Dick.",
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            Id = new Guid("1a54691c-bfd1-40f4-9c4e-43ff6d435404"),
                            Author = "Virginia Woolf",
                            PublishDate = new DateTime(1927, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A distinctive novel by Virginia Woolf that explores the concept of time, change, and human relationships.",
                            Title = "To the Lighthouse"
                        });
                });

            modelBuilder.Entity("Library.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
