// <auto-generated />
using System;
using Library.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Library.API.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20230804092052_Initial2")]
    partial class Initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.20");

            modelBuilder.Entity("Library.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b915ca4-ac42-4890-83c3-0f806b449d1a"),
                            Author = "Harper Lee",
                            PublishDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A powerful novel set in the American South during the struggle for civil rights and social justice.",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = new Guid("0fc3776d-d081-4fe5-8262-05cdd7e5b7a4"),
                            Author = "George Orwell",
                            PublishDate = new DateTime(1949, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A dystopian and political science fiction novel that depicts a society controlled by a totalitarian government.",
                            Title = "1984"
                        },
                        new
                        {
                            Id = new Guid("57592ea6-b682-44b7-97fa-3d62f1667580"),
                            Author = "F. Scott Fitzgerald",
                            PublishDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A distinctive novel that portrays the social elite in the 1920s.",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = new Guid("d7672cee-d896-47dd-bb68-bdad921af656"),
                            Author = "J.R.R. Tolkien",
                            PublishDate = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "An epic fantasy trilogy that follows the journey of Frodo Baggins and his friends to destroy the One Ring.",
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = new Guid("6f4292ed-227c-42ac-8ae1-56a6701c612f"),
                            Author = "J.D. Salinger",
                            PublishDate = new DateTime(1951, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A famous novel that depicts teenage angst and social alienation.",
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = new Guid("70081581-6655-4133-b7a7-357285f439f6"),
                            Author = "Aldous Huxley",
                            PublishDate = new DateTime(1932, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A science fiction novel that describes an advanced future society and how technology and institutions affect humans.",
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = new Guid("7ce197bc-9071-4278-ac06-3e78601d1981"),
                            Author = "Jane Austen",
                            PublishDate = new DateTime(1813, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A classic romance novel that portrays British society in the 19th century.",
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = new Guid("97c40757-7dee-49df-bb35-7aa241b42ae2"),
                            Author = "C.S. Lewis",
                            PublishDate = new DateTime(1950, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A series of seven fantasy novels that follow the adventures of children in the magical land of Narnia.",
                            Title = "The Chronicles of Narnia"
                        },
                        new
                        {
                            Id = new Guid("38ef95f8-bdac-437d-99f6-6355654b887b"),
                            Author = "Herman Melville",
                            PublishDate = new DateTime(1851, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "An epic novel that describes the journey of sailors aboard the ship 'Pequod' to hunt a giant whale named Moby Dick.",
                            Title = "Moby-Dick"
                        },
                        new
                        {
                            Id = new Guid("6c5af8af-bb5b-411c-800e-a8094e79cb8e"),
                            Author = "Virginia Woolf",
                            PublishDate = new DateTime(1927, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShortDescription = "A distinctive novel by Virginia Woolf that explores the concept of time, change, and human relationships.",
                            Title = "To the Lighthouse"
                        });
                });

            modelBuilder.Entity("Library.Entities.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });
#pragma warning restore 612, 618
        }
    }
}
